[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "day_1",
  "day_2",
  "day_4",
  "day_6",
  "day_7",
  "day_8",
  "day_10",
  "day_13",
  "day_14",
  "day_15",
  "day_19",
]
